# yapi
apiVersion: v1
kind: Service
metadata:
  name: yapi
  namespace: yapi
spec:
  ports:
  - name: yapi
    port: 3000
    nodePort: 30300
    targetPort: 3000
  type: NodePort
  selector:
    app: yapi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yapi
  namespace: yapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yapi
  template:
    metadata:
      labels:
        app: yapi
    spec:
      containers:
      - name: yapi
        image: xcbeyond/yapi:1.9.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        args:
          # 启动参数, install: 首次安装时使用，start：后续启动时使用
          - "install"