version: '3.3'

services:
  mongodb :
    image: mongo:4.4.6
    # volumes:
    #     - /yapi/mongo/db:/data/db
    #     - /yapi/mongo/log:/var/log/mongodb
    ports:
      - 27017:27017
    # command: --auth

  yaip:
    image: xcbeyond/yapi:1.9.2
    ports:
      - 3000:3000
    command:
      # 启动参数, install: 首次安装时使用，start：后续启动时使用 
      - "install"
    depends_on: 
      - mongodb